# Generated by Django 5.0.6 on 2026-08-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('published_year', models.IntegerField()),
                ('available', models.BooleanField()),
            ],
        ),
    ]
